#!/usr/bin/env python

"""
An HTTP handler for Medusa that publishes the Asterisk setup Quixote application
"""

# A simple HTTP server, using Medusa, that publishes a Quixote application,
# based on medusa_http.py from Quixote


import medusa
from quixote import enable_ptl

print "DeStar DEVELOPMENTAL SNAPSHOT, Copyright (C) 2004 by Holger Schurig."
print "DeStar comes with ABSOLUTELY NO WARRANTY. This is free software,"
print "you are welcome to redistribute it under certain conditions;"
print "see the included files GPL-2.txt and COPYRIGHT.txt"
print

enable_ptl()
import Publisher

s = medusa.Server("MainPage", port=8080, publisher=Publisher.DeStarPublisher)

try:
	s.run()
except KeyboardInterrupt:
	pass

